sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"abc\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"},{\"id\":88, \"username\":\"aaa\",\"password\":\"111\"}]"
    
  rabbitmq:
    host: 192.168.161.132
    port: 5672
    username: admin
    password: admin